import pandas as pd
import json
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import classification_report, accuracy_score, precision_score, recall_score, f1_score
import joblib

# Load dataset
df = pd.read_csv("data/UNSW_NB15_training-set.csv")

print("Dataset Loaded")
print(df.head())

# Encode categorical columns
label_encoders = {}

categorical_columns = ['proto', 'service', 'state']

for col in categorical_columns:
    le = LabelEncoder()
    df[col] = le.fit_transform(df[col])
    label_encoders[col] = le

# Features and target
X = df.drop(columns=['label'])
y = df['label']

# Remove attack_cat if present
if 'attack_cat' in X.columns:
    X = X.drop(columns=['attack_cat'])

# Train/test split
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

# Train model
model = RandomForestClassifier(
    n_estimators=100,
    random_state=42
)

model.fit(X_train, y_train)

# Predictions
predictions = model.predict(X_test)

# Evaluation
print(classification_report(y_test, predictions))
metrics = {
    "accuracy": round(float(accuracy_score(y_test, predictions)), 4),
    "precision": round(float(precision_score(y_test, predictions, zero_division=0)), 4),
    "recall": round(float(recall_score(y_test, predictions, zero_division=0)), 4),
    "f1": round(float(f1_score(y_test, predictions, zero_division=0)), 4)
}

# Save model
joblib.dump(model, "model/security_model.pkl")

metadata = {
    "model_name": "UNSW-NB15 Random Forest Threat Classifier",
    "model_version": "security-random-forest-v1",
    "model_type": type(model).__name__,
    "artifact_path": "model/security_model.pkl",
    "dataset": "UNSW-NB15",
    "target_column": "label",
    "dropped_columns": ["attack_cat"],
    "categorical_columns": categorical_columns,
    "expected_features": int(X.shape[1]),
    "labels": {
        "0": "normal_activity",
        "1": "threat_detected"
    },
    "baseline_metrics": metrics,
    "notes": "Generated by model/train_security_model.py"
}

with open("model/model_metadata.json", "w", encoding="utf-8") as metadata_file:
    json.dump(metadata, metadata_file, indent=2)

print("Security model trained successfully!")
